dependencies:
  - python=3
  - pip:
    - altgraph
    - appdirs
    - beautifulsoup4
    - bitshares
    - bleach
    - certifi
    - chardet
    - click
    - click-datetime
    - colorama
    - cycler
    - decorator
    - demjson
    - EasyProcess
    - ecdsa
    - entrypoints
    - Events
    - future
    - graphenelib
    - html5lib
    - idna
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jsonschema
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - lxml
    - macholib
    - MarkupSafe
    - matplotlib
    - mistune
    - msgpack-python
    - nba-py
    - nbconvert
    - nbformat
    - notebook
    - numpy
    - pandas
    - pandocfilters
    - parso
    - pefile
    - pickleshare
    - pip
    - prettytable
    - prompt-toolkit
    - pycryptodome
    - Pygments
    - pylibscrypt
    - pymongo
    - pyparsing
    - python-dateutil
    - pytz
    - PyYAML
    - pyzmq
    - QDarkStyle
    - qtconsole
    - requests
    - rqopen-client
    - scrypt
    - selenium
    - setuptools
    - simplegeneric
    - six
    - testpath
    - tornado
    - tqdm
    - traitlets
    - uptick
    - urllib3
    - vnpy
    - wcwidth
    - webencodings
    - websocket-client
    - websockets
    - widgetsnbextension
    - xlrd
    - XlsxWriter